// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHXc_JfbEYblfPcoIhjyFiAq0HdHzwWzw',
    appId: '1:703903823299:web:a713dc2a824f711dd87976',
    messagingSenderId: '703903823299',
    projectId: 'tiszapp-175fb',
    authDomain: 'tiszapp-175fb.firebaseapp.com',
    databaseURL:
        'https://tiszapp-175fb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tiszapp-175fb.appspot.com',
    measurementId: 'G-4WZ4KT7S3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUr2Eaj2V0TkHIMWYy9UCql5r0h4rkm1U',
    appId: '1:703903823299:android:e581e8d17dcddf0fd87976',
    messagingSenderId: '703903823299',
    projectId: 'tiszapp-175fb',
    databaseURL: 'https://tiszapp-175fb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tiszapp-175fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4WEryqDXNiWbyHEgYhmVsdKPUp5Hk8iE',
    appId: '1:703903823299:ios:55d4b3fea8d5e96dd87976',
    messagingSenderId: '703903823299',
    projectId: 'tiszapp-175fb',
    databaseURL: 'https://tiszapp-175fb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tiszapp-175fb.appspot.com',
    iosClientId: '703903823299-l35ulg24vjd5bdrqo2669si445i9gcej.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiszappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4WEryqDXNiWbyHEgYhmVsdKPUp5Hk8iE',
    appId: '1:703903823299:ios:55d4b3fea8d5e96dd87976',
    messagingSenderId: '703903823299',
    projectId: 'tiszapp-175fb',
    databaseURL:
        'https://tiszapp-175fb-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tiszapp-175fb.appspot.com',
    iosClientId:
        '703903823299-l35ulg24vjd5bdrqo2669si445i9gcej.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiszappFlutter',
  );
}
